//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wordcounter.com/", ConfigurationName="ServiceReference1.IWordCounter")]
    public interface IWordCounter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wordcounter.com/IWordCounter/CountWords", ReplyAction="http://wordcounter.com/IWordCounter/CountWordsResponse")]
        int CountWords(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wordcounter.com/IWordCounter/CountWords", ReplyAction="http://wordcounter.com/IWordCounter/CountWordsResponse")]
        System.Threading.Tasks.Task<int> CountWordsAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordCounterChannel : ServiceClient.ServiceReference1.IWordCounter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordCounterClient : System.ServiceModel.ClientBase<ServiceClient.ServiceReference1.IWordCounter>, ServiceClient.ServiceReference1.IWordCounter {
        
        public WordCounterClient() {
        }
        
        public WordCounterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordCounterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountWords(string text) {
            return base.Channel.CountWords(text);
        }
        
        public System.Threading.Tasks.Task<int> CountWordsAsync(string text) {
            return base.Channel.CountWordsAsync(text);
        }
    }
}
